version: "3.8"
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./cloudflared:/etc/cloudflared
    command: tunnel run --token ${CF_TUNNEL_TOKEN}

  db:
    image: mariadb:10.9
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${NEXTCLOUD_DB_NAME}
      MYSQL_USER: ${NEXTCLOUD_DB_USER}
      MYSQL_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    # ─────────────── Montages requis ───────────────
    volumes:
      # données Nextcloud
      - nextcloud_data:/var/www/html
      # votre thème personnalisé (lecture seule)
      - ./themes/my-school:/var/www/html/themes/my-school:ro
      # script d'init au démarrage
      - ./scripts/initialize.sh:/docker-entrypoint.d/initialize.sh:ro
    networks:
      - default

volumes:
  nextcloud_data:
  db_data:

