services:
  calendar:
    image: nginx:stable-alpine
    container_name: calendar
    ports: ["8081:80"]
    volumes:
      - ./calendar-app/public:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks: [web]

  imgworker:
    build: ./imgworker
    restart: unless-stopped
    volumes:
      - ./calendar-app/public/images:/mnt/images
    depends_on:
      - converter

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    command: --label-enable --cleanup --interval 86400
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  db:
    image: mariadb:10.11
    labels:
      - "com.centurylinklabs.watchtower.enable:true"
    restart: unless-stopped
    env_file: .env
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    networks: [web]

  nextcloud:
    image: nextcloud:31-apache
    labels:
    - "com.centurylinklabs.watchtower.enable:true"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
      - "./vendor:/vendor:ro"
      - "./scripts/initialize.sh:/docker-entrypoint-hooks.d/before-starting/initialize.sh:ro"
    networks:
      - web

  converter:
    build:
      context: ./converter
    environment:
      KEEP_ORIGINAL_NAMES: "1"
      IMAGE_OVERWRITE: "1"          
      #events 
      INTERVAL: 60                     
      PYTHONUNBUFFERED: "1"
      # images (optional but recommended)
      IMAGE_INTERVAL: 300
    volumes:
      - ./converter/feeds.txt:/config/feeds.txt:ro
      - ./calendar-app/public:/app/calendar-app/public
      - nextcloud_data:/ncdata:ro
    depends_on: [nextcloud]
    restart: unless-stopped
    networks: [web]

volumes:
  db_data:
  nextcloud_data:

networks:
  web:
    external: true
