services:
  calendar:
    build:
      context: ./calendar-app      # chemin vers le dossier contenant votre Dockerfile
      dockerfile: Dockerfile
    container_name: calendar
    ports:
      - "8081:80"                  # mappe le port 80 du container sur le port 8081 de l’hôte
    volumes:
      - ./calendar-app/public:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - web

  db:
    image: mariadb:10.9
    restart: unless-stopped
    env_file: .env
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - web

  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - nextcloud_data:/var/www/html
      - ./themes/my-school:/var/www/html/themes/my-school:ro
      - ./scripts/initialize.sh:/docker-entrypoint.d/initialize.sh:ro
    networks:
      - web
  converter:
    build:
      context: ./icsToJson
    env_file:
      - .env
    volumes:
      - ./calendar-app/public:/app/calendar-app/public
    depends_on:
      - nextcloud
      - calendar-app
volumes:
  db_data:
  nextcloud_data:

networks:
  web:
    external: true

