services:
  calendar:
    image: nginx:stable-alpine
    container_name: calendar
    ports: ["8081:80"]
    volumes:
      - ./calendar-app/public:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks: [web]

  db:
    image: mariadb:10.9
    restart: unless-stopped
    env_file: .env
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    networks: [web]

  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    env_file: .env
    depends_on: [db]
    ports: ["8080:80"]
    volumes:
      - nextcloud_data:/var/www/html
    networks: [web]

  converter:
    build:
      context: ./icsToJson
    environment:
      GROUP_BY_SLUG: "0"            
      KEEP_ORIGINAL_NAMES: "1"      
      IMAGE_OVERWRITE: "1"          # overwrite if same filename
      #events 
      INTERVAL: 60                     
      FEEDS_FILE: /config/feeds.txt    
      OUTPUT: /app/calendar-app/public/events.json
      PYTHONUNBUFFERED: "1"
      # images (optional but recommended)
      NC_DATA_ROOT: /ncdata
      IMAGE_SRC_TEMPLATE: "/ncdata/data/{slug}/files/Calendar"
      IMAGE_OUT_DIR: /app/calendar-app/public/images
      IMAGE_INTERVAL: 300
    volumes:
      - ./icsToJson/feeds.txt:/config/feeds.txt:ro         # ← provide feeds
      - ./calendar-app/public:/app/calendar-app/public      # ← share events.json with nginx
      - nextcloud_data:/ncdata:ro                           # ← read NC files for images
    depends_on: [nextcloud]
    restart: unless-stopped
    networks: [web]

volumes:
  db_data:
  nextcloud_data:

networks:
  web:
    external: true

