version: "3.8"
services:
  db:
    image: mariadb:10.9
    restart: unless-stopped
    env_file: .env
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - db_data:/var/lib/mysql

  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - nextcloud_data:/var/www/html
      - ./themes/my-school:/var/www/html/themes/my-school:ro
      - ./scripts/initialize.sh:/docker-entrypoint.d/initialize.sh:ro
   
  calendar-sync:
    build:
      context: ./sync
    restart: always
    env_file: .env        # bring in ICS_URL, DEST_DIR, etc.
    volumes:
      - calendar-data:/data

volumes:
  db_data:
  nextcloud_data:
  calendar-data:
