services:
  calendar:
    image : nginx:stable-alpine
    container_name: calendar
    ports:
      - "8081:80"                 
    volumes:
      - ./calendar-app/public:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks: [web]

  db:
    image: mariadb:10.9
    restart: unless-stopped
    env_file: .env
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    networks: [internal]

  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    env_file: .env
    depends_on: [db]
    ports:
      - "8083:80"
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - nextcloud_data:/var/www/html
      - ./themes/my-school:/var/www/html/themes/my-school:ro
      - ./scripts/initialize.sh:/docker-entrypoint.d/initialize.sh:ro
    networks:
      - internal
      - web

  converter:
    build:
      context: ./icsToJson
    environment:
      INTERVAL: 60
      FEEDS_FILE: /config/feeds.txt
      OUTPUT: /app/calendar-app/public/events.json
      NC_DATA_ROOT: /ncdata
      IMAGE_SRC_TEMPLATE: "/ncdata/data/{slug}/files/Calendar"
      IMAGE_SRC_REI: /ncdata/data/rei/files/Calendar
      IMAGE_OUT_DIR: /app/calendar-app/public/images
      IMAGE_INTERVAL: 300
      PYTHONUNBUFFERED: "1"
    volumes:
      - nextcloud_data:/ncdata:ro
      - ./calendar-app/public:/app/calendar-app/public
      - ./icsToJson/feeds.txt:/config/feeds.txt:ro
    depends_on: [nextcloud]
    restart: unless-stopped
    networks: [internal]

volumes:
  db_data:
  nextcloud_data:

networks:
  web:
    external: true
  internal:
    driver: bridge

